### ISSUE TITLE
使用mgithub repocache，无法导入repo列表到清单文件

### ISSUE THREAD

**Issue by qiaofeng1227** [Websoft9/mgithub#9]
初次执行copy命令,提示如下
```
开始更新qiaofeng1227 Github仓库列表...

您的仓库列表为空,请检查您的网络连接或组织名称
```
执行mgithub repocache，列表清单为空，再次执行报错
```
[root@VM-81-187-centos data]# mgithub repocache
Traceback (most recent call last):
  File "/usr/lib64/python3.6/configparser.py", line 846, in items
    d.update(self._sections[section])
KeyError: 'mgithub'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/mgithub", line 11, in <module>
    load_entry_point('mgithub', 'console_scripts', 'mgithub')()
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1256, in invoke
    Command.invoke(self, ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/data/mgithub/GithubCLI.py

```

**Comment by qiaofeng1227** [comment]
Done
